- name: Install Node.js
  hosts: kn-node
  become: true
  vars:
    nodejs_version: "18.x"
    nodejs_install_npm_user: "{{ ansible_ssh_user }}"
    nodejs_npm_global_packages:
      - name: pm2
      - name: pnpm
  roles:
    - geerlingguy.nodejs
